url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Avon Park Historical Society" # the name of your site, e.g. ACME Corp.

collections:
  pages:
    output: true
  articles:
    output: true
  photos:
    output: true
  quizzes:
    output: true
  podcasts:
    output: true
  events:
    output: true

sass:
  sass_dir: _sass
  style: expanded
