backend:
  name: github
  repo: Avon-Park-Historical-Society/avonparkhistoricalsociety.com

media_folder: /assets/photos
public_folder: /

collections:
  - name: articles
    label: Articles
    label_singular: Article
    folder: /_articles
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }
